# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by setup_project
# This file reflects the paths in the primary pipeline
# configuration defined for this project.

Windows: 'Z:\mnt\software\shotgun\test'
Darwin: '/mnt/software/shotgun/test'
Linux: '/mnt/software/shotgun/test'

# End of file.
